import type { NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react'

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Personal Assistant Service | Fastwork.co</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Fragment>
  )
}

export default Home
